---
- project:
    check:
      jobs:
        - pre-commit
        - sandcastle-tests
    gate:
      jobs:
        - pre-commit

- job:
    # job names are global, this should be unique
    name: sandcastle-tests
    parent: oc-cluster-up
    description: Deploy a cluster and run tests
    pre-run:
      - files/setup-openshift.yaml
      - files/install-test-dependencies.yaml
    extra-vars:
      with_testing: true
    run: files/zuul-tests.yaml
