---
- name: Install dependencies for sandcastle.
  hosts: all
  tasks:
  - name: Install basic utilities which should be in a sandbox.
    dnf:
      name:
      - make
      - git-core
      - packit
      - rpmdevtools
      - automake
      - autoconf
      - libtool  # https://github.com/TomasTomecek/libnbd/pull/1#issuecomment-554378236
      - tito
      - cmake
      - meson
      - ninja-build
      - wget
      - curl
      - findutils
      - which
      - npm  # cockpit project needs these
      - python3-docutils  # for those who generates man pages from README.md
      - json-c-devel  # \
      - systemd-devel # https://github.com/Scribery/tlog/pull/274
      - libcurl-devel # /
      - python3-zanata-client # for those who use zanata for localization
      - python2             # https://github.com/packit-service/sandcastle/issues/49
      - python2-setuptools  # /

      - python3-black  # libmodulemd
      - clang
      - clang-analyzer
      - clang-tools-extra
      - createrepo_c
      - libmodulemd
      - elinks
      - file-devel
      - gcc
      - gcc-c++
      - git-core
      - glib2-devel
      - glib2-doc
      - gobject-introspection-devel
      - gtk-doc
      - libyaml-devel
      - ninja-build
      - openssl
      - pkgconf
      - popt-devel
      - python2-devel
      - python2-six
      - python2-gobject-base
      - python3-autopep8
      - python3-devel
      - python3-GitPython
      - python3-gobject-base
      - python3-pycodestyle
      - python3-rpm-macros
      - redhat-rpm-config
      - rpm-build
      - rpm-devel
      - rpmdevtools
      - ruby
      - "rubygem(json)"
      - sudo
      - rubygems
      - valgrind

      state: present
      install_weak_deps: no # on F30 python2 pulls in unwanted python-unversioned-command
    tags:
    - basic-image

  - name: Install all RPM packages needed to hack on sandcastle.
    dnf:
      name:
      - git-core
      - python3-devel
      - python3-ipdb  # for easy debugging
      - python3-pip
      - python3-setuptools
      - python3-setuptools_scm
      - python3-setuptools_scm_git_archive
      - origin-clients  # oc cp
      - python3-pytest  # tests
      - python3-flexmock
      - python3-kubernetes
      state: present
    tags:
    - with-sandcastle-deps
#   - name: Install python-kube
#     block:
#     - name: tmpdir
#       tempfile:
#         state: directory
#       register: tmpdir
#     - name: clone to tmpdir
#       git:
#         repo: https://github.com/TomasTomecek/kubernetes-python.git
#         recursive: true
#         dest: '{{ tmpdir.path }}'
#     - name: install
#       pip:
#         executable: /usr/bin/pip3
#         name: 'file://{{ tmpdir.path }}'
#     - name: clean tmpdir
#       file:
#         path: '{{ tmpdir.path }}'
#         state: absent
#     tags:
#     - with-sandcastle-deps
  - name: Install tests requirements
    pip:
      executable: /usr/bin/pip3
      requirements: "{{ lookup('env','PWD') }}/tests/requirements.txt"
    tags:
    - with-sandcastle-deps
