---
- name: Install test dependencies
  hosts: all
  tasks:
    - name: dnf install pytest & flexmock
      dnf:
        name:
          - python3-pytest
          - python3-flexmock
        state: present
      become: true
