---
- name: Build test image & run tests
  hosts: all
  tasks:
    - include_tasks: tasks/zuul-project-setup.yaml
    - name: Build test image
      command: make test-image-build
      args:
        chdir: "{{ project_dir }}"
      become: true
    - name: Run tests
      command: make check
      args:
        chdir: "{{ project_dir }}"
      become: true
